Code review for first milestone
orestis-kaplan/calculator pull request #1
Opened 2019-09-11 02:46 UTC by userman95

2019-09-11 13:03 UTC, rvvergara requested changes
## Hi @userman95,

Welcome to React! :)

Ok for this first milestone I'd like you to make the ff changes:

1. Let us activate stickler/linter into this project. The instructions for doing so are in pathwright.
2. We should have deleted only `index.css`, `App.test.js`, 'serviceWorker.js`. `App.js` shouldn't have been deleted

2019-09-12 23:46 UTC, rvvergara approved these changes
## Hi @userman95,

Great, we can move forward to the next milestone! I just left a comment on eslint.config file. Kindly consider my suggestion there. But it isn't a necessary thing to merge this branch, so:

# :+1:

2019-09-12 23:46 UTC, rvvergara commented on eslint.config
> +  rules: {
It will be very helpful to you if you can copy these exact rules into your `eslintrc.js` file so locally you will not encounter errors related to this (it could be annoying :D).

2019-09-13 01:43 UTC, orestis-kaplan commented on eslint.config
> +  rules: {
True! Thanks Ryan

2019-09-13 15:48 UTC, merged