Fourth milestone
orestis-kaplan/calculator pull request #5
Opened 2019-09-28 15:13 UTC by userman95

2019-09-30 11:14 UTC, SunnyAsar requested changes
# Hi @userman95 
good job with this milestone, lets correct a few thing.
- remove commnets and log message,
- There are linting problems in the code base, i have pointed out a couple.
- please use array de structuring whenever possible.
- #### Consider grouping your css files in another directory, they are not components after all

#### Please request another review with the changes

2019-09-30 11:14 UTC, SunnyAsar commented on src/logic/operate.js
> +    console.log(numberOne, numberTwo);
Please remove the log message

2019-09-30 11:14 UTC, SunnyAsar commented on src/logic/operate.js
> +  if (operation === 'x') { return Big(numberOne).times(numberTwo).toString(); }
this is a good place to use switch instead of multiple `if`

2019-09-30 11:14 UTC, SunnyAsar commented on src/logic/calculate.js
> +    } else if (buttonName === '+/-') {
The Linting here is not right. its a little too indented.

2019-10-01 16:26 UTC, BalintMendli approved these changes
Hi @userman95 ,

All good for this milestone.

### 👍

2019-10-04 14:42 UTC, merged